version: '3'

services:
  terraform:
    image: hashicorp/terraform:1.0.1
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    volumes:
      - $DIR:/app
    working_dir: /app
